name: expo-publish

on:
  workflow_call:
    secrets:
      expo-token:
        description: 'expo token to use to publish preview'
        required: true
    inputs:
      channel:
        required: false
        type: string
        default: default

jobs:
  deploy-expo-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - uses: expo/expo-github-action@v7
        with:
          expo-cache: true
          expo-version: 5.x
          token: ${{ secrets.expo-token }}
      - run: yarn
      - run: cp .env.sample .env
      - run: expo publish --release-channel=${{ inputs.channel }} --non-interactive
      - uses: expo/expo-github-action/preview-comment@v7
        if: github.event_name == 'pull_request'
        with:
          channel: ${{ inputs.channel }}