name: expo-publish

on:
  workflow_call:
    secrets:
      expo-token:
        description: 'expo token to use to publish preview'
        required: true
    inputs:
      channel:
        required: false
        type: string
        default: default

jobs:
  deploy-expo-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: expo/expo-github-action@v6
        with:
          expo-cache: true
          expo-version: 4.x
          token: ${{ secrets.expo-token }}
      - run: yarn install
      - run: cp .env.sample .env
      - run: expo publish --release-channel=${{ inputs.channel }}
      - uses: unsplash/comment-on-pr@master
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: App is ready for review, you can [see it here](https://expo.dev/@nearform/optic-expo?release-channel=${{ inputs.channel }}).
